### ISSUE TITLE
SelectApp: factor out Vis from Schema

### ISSUE THREAD

**Issue by gwk** [gwk/pithy#6]
Currently, pithy.sqlite.schema provides a `Vis` class, and `Column` takes a `vis` argument. This is used to provide customized rendering of table cells. Since `Vis` is only relevant to SelectApp, we should move it to `pithy.web.asgi.select`, and remove the `Column.vis` property. The main reason to do this is because because it will reduce import tangles; schema definitions should not be dependent on the visualization code.

Instead, `SelectApp` should take  a constructor argument `vis` that is a nested dictionary mapping schema -> table -> column -> Vis instances.

**Comment by davlis-tr** [comment]
PR https://github.com/gwk/pithy/pull/10

**Comment by gwk** [comment]
This code was successfully merged, just not with GitHub.
