### ISSUE TITLE
SelectApp: default ORDER BY

### ISSUE THREAD

**Issue by gwk** [gwk/pithy#7]
Add a constructor argument to SelectApp `order_by` that maps schema -> table -> order_by. The value should be an SQL expression that gets passed into `render_table`.

**Comment by davlis-tr** [comment]
PR https://github.com/gwk/pithy/pull/11

**Comment by gwk** [comment]
Refactored slightly to validate the `order_by` schema/table keys and default to empty dictionaries, which simplifies the lookup code.
